name: deploy-callable
on:
  workflow_call:
    inputs:
      location:
        type: string
        required: true
      prefix:
        type: string
        required: true
      suffix_salt:
        type: string
        required: true
      use_single_resource_group:
        type: boolean
        required: true
      enable_application_containers:
        type: boolean
        required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ secrets.AZ_CLIENT_ID }}","clientSecret":"${{ secrets.AZ_CLIENT_SECRET }}","subscriptionId":"${{ secrets.AZ_SUBSCRIPTION_ID }}","tenantId":"${{ secrets.AZ_TENANT_ID }}"}'
      - uses: azure/arm-deploy@v1
        with:
          scope: subscription
          subscriptionId: ${{ secrets.AZ_SUBSCRIPTION_ID }}
          region: ${{ inputs.location }}
          template: ./infrastructure.bicep
          deploymentName: dpl-${{ inputs.prefix }}-${{ github.run_id }}
          parameters: batchServiceObjectId=${{ secrets.AZ_BATCH_SERVICE_OBJECT_ID }} prefix=${{ inputs.prefix }} suffixSalt="${{ inputs.suffix_salt }}" useSingleResourceGroup=${{ inputs.use_single_resource_group }} tags="{'github-action':'1', 'github-run-id':'${{ github.run_id }}'}" enableApplicationContainers=${{ inputs.enable_application_containers }}
      - name: cleanup
        if: success() || failure()
        run: |
          az deployment sub show -n dpl-${{ inputs.prefix }}-${{ github.run_id }} --query properties.outputs
          az group list --tag "github-run-id=${{ github.run_id }}" --query "[].name" -o tsv
          az group list --tag "github-run-id=${{ github.run_id }}" --query "[].name" -o tsv | xargs -l az group delete --yes --no-wait --name
